"""empty message

Revision ID: ad33e5e7d3ec
Revises: d7210807e87a
Create Date: 2023-04-28 22:57:47.570793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad33e5e7d3ec'
down_revision = 'd7210807e87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie', 'ranking',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie', 'review',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'review',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movie', 'ranking',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
